// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXRxKl_4vmZJnrkcnVzEj9bWMiI4tpN_0',
    appId: '1:306516928864:web:f095565ff7bcafa71c5605',
    messagingSenderId: '306516928864',
    projectId: 'my-health-app-bb127',
    authDomain: 'my-health-app-bb127.firebaseapp.com',
    storageBucket: 'my-health-app-bb127.firebasestorage.app',
    measurementId: 'G-TFKYP4B3S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeu7egds-iQOPzIwEnrpTjsXJ7GSDqHfI',
    appId: '1:306516928864:android:f0b2dae3cf7946791c5605',
    messagingSenderId: '306516928864',
    projectId: 'my-health-app-bb127',
    storageBucket: 'my-health-app-bb127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxRVnAFZv3Qr4vb1J2wPLjR5dcx0Y7JGQ',
    appId: '1:306516928864:ios:323ce64207679d641c5605',
    messagingSenderId: '306516928864',
    projectId: 'my-health-app-bb127',
    storageBucket: 'my-health-app-bb127.firebasestorage.app',
    iosBundleId: 'com.example.myhealthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxRVnAFZv3Qr4vb1J2wPLjR5dcx0Y7JGQ',
    appId: '1:306516928864:ios:323ce64207679d641c5605',
    messagingSenderId: '306516928864',
    projectId: 'my-health-app-bb127',
    storageBucket: 'my-health-app-bb127.firebasestorage.app',
    iosBundleId: 'com.example.myhealthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXRxKl_4vmZJnrkcnVzEj9bWMiI4tpN_0',
    appId: '1:306516928864:web:9a3e1b5fbe6f55481c5605',
    messagingSenderId: '306516928864',
    projectId: 'my-health-app-bb127',
    authDomain: 'my-health-app-bb127.firebaseapp.com',
    storageBucket: 'my-health-app-bb127.firebasestorage.app',
    measurementId: 'G-N10JFNDF0H',
  );
}
